name: agri_vision
description: "AgriVision - AI for Agriculture"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.10.3
  intl: ^0.19.0
  fluttertoast: ^8.2.2
  provider: ^6.0.5
  file_picker: ^10.3.7
  google_generative_ai: ^0.4.3
  fl_chart: ^0.69.0
  csv: ^6.0.0
  pdf: ^3.10.7
  printing: ^5.11.0
  flutter_dotenv: ^6.0.0   
  image_picker: ^1.0.0      
  tflite_flutter: ^0.12.1
  image: ^4.0.0          
  camera: ^0.11.3
  video_player: ^2.10.1
  permission_handler: ^12.0.1
  video_thumbnail: ^0.5.3
  device_info_plus: ^10.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.svg
    - assets/images/logo.png
    - .env
    - assets/models/model_unquant.tflite
    - assets/models/labels.txt
    - assets/images/qr_app.png
    - assets/images/qr_dataset.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
