name: agri_vision
description: "AgriVision - AI for Agriculture"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.10.3
  intl: ^0.19.0
  fluttertoast: ^8.2.2
  image_picker: ^1.1.0
  provider: ^6.0.5
  file_picker: ^8.0.0
  google_generative_ai: ^0.4.3
  fl_chart: ^0.69.0
  csv: ^6.0.0
  pdf: ^3.10.7
  printing: ^5.11.0
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.svg
    - assets/images/logo.png
    - assets/images/sample_ripen.png
    - assets/images/sample_unripe.png
    - assets/images/sample_disease.png
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
